### ISSUE TITLE
unicode 12.0+ characters not supported

### ISSUE THREAD

**Issue by grenzionky** [mikekap/unicodedata2#33]
None of the new characters since unicode 12.0 are recognized.

Doing
```
>>> import unicodedata
>>> unicodedata.name('𛅥') # or any other of the new characters like ᳺ or 𛅐
```
returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: no such name
```

I'm using `python3.7` with `unicodedata2-12.1.0`

**Comment by Harmon758** [comment]
You're importing [the standard library, `unicodedata`](https://docs.python.org/3.7/library/unicodedata.html), rather than this library, `unicodedata2`.
Note, 𛅥, ᳺ, and 𛅐 are all part of Unicode 12.0, while [Python 3.7's `unicodedata` uses Unicode 11](https://docs.python.org/3.7/whatsnew/3.7.html#unicodedata).
([Unicode 12.1](https://www.unicode.org/versions/Unicode12.1.0/) only included ㋿.)
If you want an in-place replacement for `unicodedata`, you can simply `import unicodedata2 as unicodedata`.
